baseURL = 'https://example.org/'
locale = 'en-us'
title = 'bookmarks'
theme = 'searchwind'

contentDir = "../content"

[params]
    logo = 'home'
    showCategoriesMenu = false
    showTagsMenu = true

[params.usersettings]
    sidebar = "right" # left/right
    
[params.colors.light]
    bg = "#1fd756"
    bg_card = "#FFFFFF"
